export const homeObjOne = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Premium Bank',
  headLine: 'Unlimited Transactions with zero fees',
  description: 'Get access to our exclusive app that allows you to send unlimited transactions without any fees charged',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../images/undraw_mobile_pay.svg').default,
  alt: 'Car',
  //dark: true,
  primary: true,
  darkText: false,
}

export const homeObjTwo = {
  id: 'discover',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Lightening fast speed',
  headLine: 'No more waiting for transactions to settle',
  description: 'Settle global transactions in a matter of seconds using our cutting edge, industry leading technology',
  buttonLabel: 'Get started',
  imgStart: true,
  img: require('../../images/undraw_savings.svg').default,
  alt: 'Piggy Bank',
  //dark: false,
  primary: false,
  darkText: true,
}

export const homeObjThree = {
  id: 'services',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Lightening fast speed',
  headLine: 'Unlimited Transactions with zero fees',
  description: 'Get access to our exclusive app that allows you to send unlimited transactions without any fees charged',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../images/undraw_transfer_money.svg').default,
  alt: 'Car',
  // dark: false,
  primary: true,
  darkText: false,
}
